'use strict';
const $=id=>document.getElementById(id);let csrf='',draft,parameters=[],busy=false,aiProposal=null,aiPrevious=null,recommendedProfile='';
const initial=()=>({local_id:crypto.randomUUID(),name:'Rolka scroll do pilota LG Magic MR21 MR22 MR23 zamiennik druk 3D',price:'18.00',stock:1000,reference:'18866219051',category:'',product_id:'',producer_id:'',safety:'',ai_facts:'Rolka zamienna scroll do pilota LG Magic MR21, MR22 i MR23, w tym MR23GN. Jedna czarna rolka w zestawie, bez pilota. Technologia druk 3D. Nie opisuj materiału. Po rozebraniu pilota wymienia się uszkodzoną rolkę na nową. Ze względu na serie produkcyjne trzpień może wymagać minimalnego dopasowania, delikatnego spiłowania.',images:[],product_parameters:[],offer_parameters:[],sections:[
{title:'Rolka zamienna do pilota LG Magic',text:'Część przeznaczona do wymiany uszkodzonej rolki mechanizmu przewijania. Pozwala wymienić uszkodzony element bez kupowania całego pilota.\n\nPasuje do pilotów LG Magic z serii MR21, MR22 i MR23, w tym MR23GN. Przed zakupem sprawdź oznaczenie pilota i porównaj kształt części ze zdjęciami.'},
{title:'Co otrzymujesz',text:'Jedną czarną rolkę zamienną, wykonaną w technologii druku 3D.\n\nOferta dotyczy samej części. Pilot pokazany na zdjęciu przedstawia jej zastosowanie i nie jest dołączony do zestawu.'},
{title:'Montaż',text:'Wymianę można wykonać samodzielnie. Po rozebraniu pilota należy wyjąć uszkodzoną rolkę i zastąpić ją nową. Przed rozpoczęciem pracy wyjmij baterie.\n\nPrzed złożeniem obudowy sprawdź, czy część jest prawidłowo osadzona i porusza się swobodnie.'},
{title:'Ważna informacja o dopasowaniu',text:'Ze względu na różnice między seriami produkcyjnymi pilotów LG, w pojedynczych przypadkach trzpień może wymagać minimalnego dopasowania — delikatnego spiłowania.\n\nSprawdź spasowanie przed złożeniem pilota i nie wciskaj części na siłę. Wymiana rolki nie usuwa usterek elektroniki pilota.'}]});
function notice(s,error=false){$('notice').style.display='block';$('notice').textContent=s;$('notice').style.background=error?'#ffe9e5':'#fff5db';}
async function call(path,data){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF':csrf},body:JSON.stringify(data)});const j=await r.json();if(!r.ok)throw Error(j.error||'Błąd operacji');return j;}
function action(id,fn){$(id).onclick=async()=>{if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){notice(e.message,true);}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}};}
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function collect(){for(const [key,id]of Object.entries({ai_facts:'ai-facts',name:'name',price:'price',stock:'stock',reference:'reference',category:'category',product_id:'product-id',producer_id:'producer',safety:'safety'}))draft[key]=$(id).value;
if(parameters.length){draft.product_parameters=[];draft.offer_parameters=[];for(const p of parameters){const v=$('param-'+p.id);if(!v)continue;let result;if(p.type==='dictionary'){const ids=[...v.selectedOptions].map(x=>x.value).filter(Boolean);if(ids.length){result={id:p.id,valuesIds:ids};const custom=$('custom-'+p.id);if(custom?.value.trim()&&ids.includes(p.options?.ambiguousValueId))result.values=[custom.value.trim()];}}else if(v.value.trim())result={id:p.id,values:v.value.split(';').map(s=>s.trim()).filter(Boolean)};if(result)(p.options?.describesProduct?draft.product_parameters:draft.offer_parameters).push(result);}}return draft;}
function imagePlan(secs,images){const used=new Set();const rows=secs.map((s,i)=>{let idx=s.image_index??(i<images.length?i:-1);if(!Number.isInteger(idx)||idx<0||idx>=images.length||used.has(idx))idx=-1;else used.add(idx);return idx;});return {rows,remaining:images.map((_,i)=>i).filter(i=>!used.has(i))};}
function spreadImages(secs,count){secs.forEach(s=>s.image_index=-1);for(let i=0;i<Math.min(count,secs.length);i++){const pos=Math.floor(i*secs.length/Math.min(count,secs.length));secs[pos].image_index=i;}}
function render(){collect();$('preview-name').textContent=draft.name;$('preview-price').textContent=(Number(draft.price)||0).toLocaleString('pl-PL',{style:'currency',currency:'PLN'});$('preview-stock').textContent=`${draft.stock} szt. dostępnych · wysyłka w ciągu 1 dnia`;$('preview').replaceChildren();const visible=draft.sections.map((s,i)=>({...s,image_index:s.image_index??i})).filter(s=>s.text.trim()),plan=imagePlan(visible,draft.images);visible.forEach((s,i)=>{const row=el('div',undefined,'offer-row'),text=el('div');text.append(el('h3',s.title));richContent(text,s.text);const idx=plan.rows[i];if(idx>=0){const img=el('img');img.src=draft.images[idx];img.alt='Produkt — ujęcie '+(idx+1);if(i%2)row.append(text,img);else row.append(img,text);}else row.append(text);$('preview').append(row);});for(let i=0;i<plan.remaining.length;i+=2){const row=el('div',undefined,'offer-row images-only');for(const idx of plan.remaining.slice(i,i+2)){const img=el('img');img.src=draft.images[idx];img.alt='Produkt — ujęcie '+(idx+1);row.append(img);}$('preview').append(row);}}
function sections(){ $('sections').replaceChildren();draft.sections.forEach((s,i)=>{const box=el('div',undefined,'section-editor'),title=el('input'),text=el('textarea');title.value=s.title;title.setAttribute('aria-label','Nagłówek sekcji '+(i+1));text.value=s.text;text.rows=5;text.setAttribute('aria-label','Treść sekcji '+(i+1));title.oninput=()=>{s.title=title.value;render();};text.oninput=()=>{s.text=text.value;render();};const remove=el('button','Usuń sekcję','secondary');remove.onclick=()=>{draft.sections.splice(i,1);sections();render();};const choice=el('select');choice.setAttribute('aria-label','Zdjęcie dla sekcji '+(i+1));for(const idx of [-1,...draft.images.map((_,j)=>j)]){const o=el('option',idx===-1?'Sekcja bez zdjęcia':'Zdjęcie '+(idx+1));o.value=idx;choice.append(o);}choice.value=s.image_index??(i<draft.images.length?i:-1);choice.onchange=()=>{s.image_index=Number(choice.value);render();};box.append(title,text,choice,remove);$('sections').append(box);});}
function gallery(){ $('gallery').replaceChildren();draft.images.forEach((src,i)=>{const f=el('figure'),img=el('img');img.src=src;img.alt='Zdjęcie '+(i+1);f.append(img);for(const [label,fn]of [['←',()=>{if(i){for(const sec of draft.sections){if(sec.image_index===i)sec.image_index=i-1;else if(sec.image_index===i-1)sec.image_index=i;}[draft.images[i-1],draft.images[i]]=[draft.images[i],draft.images[i-1]];}}],['Usuń',()=>{draft.images.splice(i,1);for(const sec of draft.sections){if(sec.image_index===i)sec.image_index=-1;else if(sec.image_index>i)sec.image_index--;}}]]){const b=el('button',label,'secondary');b.onclick=()=>{fn();gallery();sections();render();};f.append(b);}$('gallery').append(f);});}
function fill(){for(const [key,id]of Object.entries({ai_facts:'ai-facts',name:'name',price:'price',stock:'stock',reference:'reference',category:'category',safety:'safety'}))$(id).value=draft[key]||'';for(const [key,id]of [['product_id','product-id'],['producer_id','producer']])if(draft[key]){const o=el('option',draft[key]);o.value=draft[key];$(id).append(o);$(id).value=draft[key];}sections();gallery();render();}
action('save-config',async()=>{notice((await call('/configure',{client_id:$('client-id').value,client_secret:$('client-secret').value,environment:$('environment').value})).message);$('client-secret').value='';$('connection').textContent='Konfiguracja zapisana — połącz konto';});
action('connect',async()=>{await call('/save',collect());const r=await call('/connect',{});location.href=r.url;});
action('disconnect',async()=>{notice((await call('/disconnect',{})).message);$('connection').textContent='Rozłączono';});
action('save-local',async()=>notice((await call('/save',collect())).message));
action('load-template',async()=>{const r=await call('/template',{reference:$('reference').value});$('category').value=r.category||'';$('settings-result').textContent=`Pobrano z: ${r.name}\nCennik dostawy: ${r.template.delivery?.shippingRates?.id||'brak'}\nZwroty: ${r.template.afterSalesServices?.returnPolicy?.id||'brak'}\nReklamacje: ${r.template.afterSalesServices?.impliedWarranty?.id||'brak'}\nGwarancja: ${r.template.afterSalesServices?.warranty?.id||'brak'}`;notice('Pobrano ustawienia sprzedawcy. Wczytaj parametry kategorii i uzupełnij dane nowej części.');render();await loadParameters();});
async function loadParameters(){
 const r=await call('/parameters',{category:$('category').value});parameters=r.parameters||[];
 parameters.sort((a,b)=>Number(!!(b.required||b.requiredForProduct))-Number(!!(a.required||a.requiredForProduct)));
 $('parameters').replaceChildren();const values=[...(draft.product_parameters||[]),...(draft.offer_parameters||[])];
 for(const p of parameters){const box=el('div',undefined,'parameter'),label=el('label',p.name+((p.required||p.requiredForProduct)?' *':'')),v=el(p.type==='dictionary'?'select':'input');v.id='param-'+p.id;label.htmlFor=v.id;const previous=values.find(x=>x.id===p.id);
 if(p.type==='dictionary'){v.multiple=!!p.restrictions?.multipleChoices;const empty=el('option','Wybierz');empty.value='';v.append(empty);for(const item of p.dictionary||[]){const o=el('option',item.value);o.value=item.id;o.selected=previous?.valuesIds?.includes(item.id)||false;v.append(o);}}
 else{v.value=previous?.values?.join('; ')||'';v.placeholder=p.unit||'Wartość';}v.onchange=render;box.append(label,v);
 if(p.type==='dictionary'&&p.options?.customValuesEnabled){const custom=el('input');custom.id='custom-'+p.id;custom.placeholder='Własna wartość (gdy wybierzesz „inna”)';custom.setAttribute('aria-label',p.name+' — własna wartość');custom.value=previous?.values?.join('; ')||'';custom.oninput=render;box.append(custom);}
 if(p.requiredForProduct)box.append(el('small','Wymagany dla nowego produktu'));$('parameters').append(box);}
 notice('Wczytano wymagane parametry produktu i oferty. Uzupełnij pola z gwiazdką.');
}
action('load-parameters',loadParameters);
action('search-products',async()=>{const r=await call('/products',{phrase:$('phrase').value,category:$('category').value});$('product-id').replaceChildren();const empty=el('option','Nowy produkt — użyj parametrów powyżej');empty.value='';$('product-id').append(empty);for(const p of r.products||[]){const o=el('option',p.name);o.value=p.id;$('product-id').append(o);}notice(`Znaleziono ${(r.products||[]).length} produktów. Sprawdź dokładną zgodność przed wyborem.`);});
action('load-producers',async()=>{const r=await call('/producers',{});$('producer').replaceChildren();const empty=el('option','Nie wybrano');empty.value='';$('producer').append(empty);for(const p of r.responsibleProducers||[]){const o=el('option',p.name||p.producerData?.tradeName||p.id);o.value=p.id;$('producer').append(o);}notice('Pobrano listę producentów. Wybierz producenta tej części.');});
action('save-allegro',async()=>{const data=collect();await call('/save',data);const r=await call('/draft',data);$('saved-status').textContent=r.id?'Szkic Allegro: '+r.id:'Zapis oczekuje na sprawdzenie statusu';showAllegro(r);});
action('check-status',async()=>{const r=await call('/status',{});$('saved-status').textContent=`Oferta ${r.id}: ${r.publication?.status||'status w trakcie ustalania'}`;showAllegro(r);});
action('publish',async()=>{if(!$('confirm').checked)throw Error('Najpierw sprawdź ofertę i zaznacz potwierdzenie publikacji.');if(!window.confirm(`Opublikować na wybranym koncie Allegro za ${$('price').value} zł, ${$('stock').value} szt.?`))return;const r=await call('/publish',{confirm:true,draft:collect()});showAllegro(r);});
$('add-section').onclick=()=>{draft.sections.push({title:'',text:''});sections();render();};
$('photos').onchange=async e=>{try{const files=[...e.target.files];if(draft.images.length+files.length>10)throw Error('Maksymalnie 10 zdjęć.');for(const f of files){if(!['image/png','image/jpeg'].includes(f.type)||f.size>10000000)throw Error('Dodaj PNG/JPG do 10 MB.');const src=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f);});if(draft.images.reduce((n,s)=>n+s.length,0)+src.length>34000000)throw Error('Zdjęcia przekraczają łączny limit 25 MB.');draft.images.push(src);}gallery();sections();render();}catch(e){notice(e.message,true);}finally{$('photos').value='';}};
for(const id of ['name','price','stock','category','safety','producer','product-id'])$(id).addEventListener('input',()=>{if(draft)render();});
(async()=>{try{const r=await(await fetch('/state')).json();csrf=r.csrf;recommendedProfile=r.ai?.recommended_profile||'';$('ai-provider').value=r.ai?.provider||'gemini';$('ai-model').value=r.ai?.model||'gpt-4.1-mini';$('ai-profile').value=r.ai?.profile||'';$('ai-key').placeholder=r.ai?.has_key?'Klucz zapisany — zostaw puste, by zachować':'Wpisz klucz wybranego dostawcy';$('client-id').value=r.client_id;$('client-secret').placeholder=r.has_secret?'Zapisany — zostaw puste, by zachować':'';$('environment').value=r.environment;$('connection').textContent=(r.connected?'Konto połączone':'Konto niepołączone')+(r.environment==='sandbox'?' · Sandbox':' · Allegro');$('config').open=!r.connected;draft=r.draft||initial();fill();if(r.saved_offer?.id)$('saved-status').textContent='Zapisana oferta: '+r.saved_offer.id;}catch(e){notice('Nie można uruchomić panelu: '+e.message,true);}})();

action('save-ai',async()=>{notice((await call('/ai-config',{provider:$('ai-provider').value,api_key:$('ai-key').value,model:$('ai-model').value,profile:$('ai-profile').value})).message);$('ai-key').value='';});
action('remove-ai-key',async()=>{notice((await call('/ai-remove-key',{})).message);$('ai-key').value='';$('ai-key').placeholder='Wpisz klucz wybranego dostawcy';});
action('generate-ai',async()=>{await call('/save',collect());$('ai-progress').textContent='Przygotowuję opis na podstawie danych produktu…';try{aiProposal=await call('/ai-generate',{facts:$('ai-facts').value,images:$('ai-use-images').checked?await compactImages(draft.images):[]});$('ai-output').replaceChildren(el('h3',aiProposal.name));for(const s of aiProposal.sections){$('ai-output').append(el('h3',s.title));const p=el('div');richContent(p,s.text);$('ai-output').append(p);}$('ai-questions').replaceChildren();if(aiProposal.questions.length){for(const q of aiProposal.questions)$('ai-questions').append(el('p','• '+q));}else $('ai-questions').append(el('p','Sprawdź poprawność danych i zgodność z produktem przed zastosowaniem.'));$('ai-proposal').hidden=false;$('ai-progress').textContent='Propozycja gotowa ('+aiProposal.sections.map(s=>s.text).join(' ').split(/\s+/).length+' słów). Sprawdź ją przed zastosowaniem.';}catch(e){$('ai-progress').textContent='Nie zmieniono obecnego opisu.';throw e;}});
$('apply-ai').onclick=()=>{if(!aiProposal||busy)return;aiPrevious={name:draft.name,sections:JSON.parse(JSON.stringify(draft.sections))};draft.name=aiProposal.name;draft.sections=JSON.parse(JSON.stringify(aiProposal.sections));if(!$('ai-use-images').checked)spreadImages(draft.sections,draft.images.length);$('name').value=draft.name;sections();render();$('confirm').checked=false;$('undo-ai').hidden=false;notice('Zastosowano propozycję. Sprawdź opis i zapisz szkic przed publikacją.');};
$('dismiss-ai').onclick=()=>{$('ai-proposal').hidden=true;aiProposal=null;};
$('undo-ai').onclick=()=>{if(!aiPrevious||busy)return;draft.name=aiPrevious.name;draft.sections=aiPrevious.sections;$('name').value=draft.name;sections();render();aiPrevious=null;$('undo-ai').hidden=true;$('confirm').checked=false;notice('Przywrócono poprzedni opis.');};

function richContent(parent,text){let list=null;for(const line of text.split('\n')){if(!line.trim()){list=null;continue;}let n;if(line.startsWith('- ')){if(!list){list=el('ul');parent.append(list);}n=el('li');list.append(n);}else{list=null;n=el('p');parent.append(n);}const parts=(line.startsWith('- ')?line.slice(2):line).split(/(\*\*.*?\*\*)/g);for(const part of parts)n.append(part.startsWith('**')&&part.endsWith('**')?el('strong',part.slice(2,-2)):document.createTextNode(part));}}
$('ai-provider').onchange=()=>{$('ai-key').value='';$('ai-key').placeholder='Wpisz klucz tego dostawcy';$('ai-model').value=$('ai-provider').value==='gemini'?'gemini-2.5-flash-lite':'gpt-4.1-mini';};
let folderGroups=new Map();
$('product-folders').onchange=e=>{folderGroups=new Map();for(const f of e.target.files){const parts=f.webkitRelativePath.split('/');parts.pop();const folder=parts.join('/');if(!folderGroups.has(folder))folderGroups.set(folder,[]);folderGroups.get(folder).push(f);}for(const [folder,files]of folderGroups)if(!files.some(f=>/\.(png|jpe?g)$/i.test(f.name)))folderGroups.delete(folder);$('folder-choice').replaceChildren();for(const [folder,files]of folderGroups){const o=el('option',folder+' · '+files.filter(f=>/\.(png|jpe?g)$/i.test(f.name)).length+' zdjęć');o.value=folder;$('folder-choice').append(o);}$('folder-info').textContent='Znaleziono produktów: '+folderGroups.size;};
action('import-folder',async()=>{
 const folder=$('folder-choice').value,files=folderGroups.get(folder);if(!files)throw Error('Najpierw wybierz folder ze zdjęciami.');
 await call('/save',collect());const pictures=files.filter(f=>/\.(png|jpe?g)$/i.test(f.name)).sort((a,b)=>a.name.localeCompare(b.name,'pl',{numeric:true}));
 if(pictures.length>10||pictures.some(f=>f.size>10000000)||pictures.reduce((n,f)=>n+f.size,0)>25000000)throw Error('Limit produktu: 10 zdjęć, 10 MB na plik i 25 MB łącznie.');
 const note=files.find(f=>/^(opis|produkt)\.txt$/i.test(f.name));if(note&&note.size>20000)throw Error('Plik opisu przekracza 20 KB.');
 const imported=initial();imported.local_id=crypto.randomUUID();imported.name=folder.split('/').pop();imported.folder=folder;imported.price='';imported.stock='';imported.sections=[];imported.ai_facts=note?await note.text():'';imported.images=[];
 for(const f of pictures)imported.images.push(await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(Error('Nie można odczytać zdjęcia. Pobierz plik z OneDrive na komputer.'));r.readAsDataURL(f);}));
 const response=await call('/switch-folder',{folder,draft:imported});draft=response.draft;parameters=[];$('parameters').replaceChildren();
 for(const id of ['producer','product-id']){const option=el('option','Nie wybrano');option.value='';$(id).replaceChildren(option);}
 aiProposal=null;aiPrevious=null;$('ai-proposal').hidden=true;$('confirm').checked=false;fill();
 $('saved-status').textContent=response.saved_offer?.id?'Oferta: '+response.saved_offer.id:'Nowy produkt — nie wysłano do Allegro';
 $('folder-info').textContent='Wczytano: '+folder+'. Sprawdź zdjęcia, fakty, cenę i ilość. Dane tego produktu są zapisane osobno.';
 notice(draft.ai_facts?'Wczytano zdjęcia i zapisane dane. Możesz wygenerować opis.':'Wczytano zdjęcia. Uzupełnij „Co wiemy o produkcie?” albo dodaj opis.txt w folderze. Nazwa folderu nie jest dowodem kompatybilności.');
});

$('reset-style').onclick=()=>{$('ai-profile').value=recommendedProfile;notice('Wstawiono styl NetStore. Kliknij Zapisz ustawienia AI.');};

function showAllegro(r){const summary=NetstoreMessages.summarize(r);$('allegro-result').hidden=false;$('result-title').textContent=summary.title;$('result-list').replaceChildren();if(summary.hasValidation&&!summary.errors.length)$('result-list').append(el('p','Brak błędów walidacji.'));for(const msg of summary.errors)$('result-list').append(el('p','Do poprawy: '+msg));if(summary.warnings.length)$('result-list').append(el('h3','Sprawdź przed publikacją'));for(const msg of summary.warnings)$('result-list').append(el('p',msg));$('result-details').textContent=JSON.stringify(r,null,2);notice(summary.title+(summary.warnings.length?' Uwagi ('+summary.warnings.length+') znajdziesz w sekcji zapisu oferty.':''),!!summary.errors.length);}
async function compactImages(images){const result=[];for(const src of images.slice(0,10)){result.push(await new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{const scale=Math.min(1,768/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.82));};img.onerror=()=>reject(Error('Nie można przygotować zdjęcia dla AI.'));img.src=src;}));}return result;}
