'use strict';
const $=id=>document.getElementById(id);let csrf='',draft,parameters=[],busy=false;
const initial=()=>({local_id:crypto.randomUUID(),name:'Rolka scroll do pilota LG Magic MR21 MR22 MR23 zamiennik druk 3D',price:'18.00',stock:1000,reference:'18866219051',category:'',product_id:'',producer_id:'',safety:'',images:[],product_parameters:[],offer_parameters:[],sections:[
{title:'Rolka zamienna do pilota LG Magic',text:'Część przeznaczona do wymiany uszkodzonej rolki mechanizmu przewijania. Pozwala wymienić uszkodzony element bez kupowania całego pilota.\n\nPasuje do pilotów LG Magic z serii MR21, MR22 i MR23, w tym MR23GN. Przed zakupem sprawdź oznaczenie pilota i porównaj kształt części ze zdjęciami.'},
{title:'Co otrzymujesz',text:'Jedną czarną rolkę zamienną, wykonaną w technologii druku 3D.\n\nOferta dotyczy samej części. Pilot pokazany na zdjęciu przedstawia jej zastosowanie i nie jest dołączony do zestawu.'},
{title:'Montaż',text:'Wymianę można wykonać samodzielnie. Po rozebraniu pilota należy wyjąć uszkodzoną rolkę i zastąpić ją nową. Przed rozpoczęciem pracy wyjmij baterie.\n\nPrzed złożeniem obudowy sprawdź, czy część jest prawidłowo osadzona i porusza się swobodnie.'},
{title:'Ważna informacja o dopasowaniu',text:'Ze względu na różnice między seriami produkcyjnymi pilotów LG, w pojedynczych przypadkach trzpień może wymagać minimalnego dopasowania — delikatnego spiłowania.\n\nSprawdź spasowanie przed złożeniem pilota i nie wciskaj części na siłę. Wymiana rolki nie usuwa usterek elektroniki pilota.'}]});
function notice(s,error=false){$('notice').style.display='block';$('notice').textContent=s;$('notice').style.background=error?'#ffe9e5':'#fff5db';}
async function call(path,data){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF':csrf},body:JSON.stringify(data)});const j=await r.json();if(!r.ok)throw Error(j.error||'Błąd operacji');return j;}
function action(id,fn){$(id).onclick=async()=>{if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){notice(e.message,true);}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}};}
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function collect(){for(const [key,id]of Object.entries({name:'name',price:'price',stock:'stock',reference:'reference',category:'category',product_id:'product-id',producer_id:'producer',safety:'safety'}))draft[key]=$(id).value;
if(parameters.length){draft.product_parameters=[];draft.offer_parameters=[];for(const p of parameters){const v=$('param-'+p.id);if(!v)continue;let result;if(p.type==='dictionary'){const ids=[...v.selectedOptions].map(x=>x.value).filter(Boolean);if(ids.length)result={id:p.id,valuesIds:ids};}else if(v.value.trim())result={id:p.id,values:v.value.split(';').map(s=>s.trim()).filter(Boolean)};if(result)(p.options?.describesProduct?draft.product_parameters:draft.offer_parameters).push(result);}}return draft;}
function render(){collect();$('preview-name').textContent=draft.name;$('preview-price').textContent=(Number(draft.price)||0).toLocaleString('pl-PL',{style:'currency',currency:'PLN'});$('preview-stock').textContent=`${draft.stock} szt. dostępnych · wysyłka w ciągu 1 dnia`;$('preview').replaceChildren();draft.sections.forEach((s,i)=>{if(!s.text.trim())return;const row=el('div',undefined,'offer-row'),text=el('div');text.append(el('h3',s.title));s.text.split('\n\n').forEach(t=>text.append(el('p',t)));if(draft.images[i]){const img=el('img');img.src=draft.images[i];img.alt='Zdjęcie części';if(i%2)row.append(text,img);else row.append(img,text);}else row.append(text);$('preview').append(row);});}
function sections(){ $('sections').replaceChildren();draft.sections.forEach((s,i)=>{const box=el('div',undefined,'section-editor'),title=el('input'),text=el('textarea');title.value=s.title;title.setAttribute('aria-label','Nagłówek sekcji '+(i+1));text.value=s.text;text.rows=5;text.setAttribute('aria-label','Treść sekcji '+(i+1));title.oninput=()=>{s.title=title.value;render();};text.oninput=()=>{s.text=text.value;render();};const remove=el('button','Usuń sekcję','secondary');remove.onclick=()=>{draft.sections.splice(i,1);sections();render();};box.append(title,text,remove);$('sections').append(box);});}
function gallery(){ $('gallery').replaceChildren();draft.images.forEach((src,i)=>{const f=el('figure'),img=el('img');img.src=src;img.alt='Zdjęcie '+(i+1);f.append(img);for(const [label,fn]of [['←',()=>{if(i)[draft.images[i-1],draft.images[i]]=[draft.images[i],draft.images[i-1]];}],['Usuń',()=>draft.images.splice(i,1)]]){const b=el('button',label,'secondary');b.onclick=()=>{fn();gallery();render();};f.append(b);}$('gallery').append(f);});}
function fill(){for(const [key,id]of Object.entries({name:'name',price:'price',stock:'stock',reference:'reference',category:'category',safety:'safety'}))$(id).value=draft[key]||'';for(const [key,id]of [['product_id','product-id'],['producer_id','producer']])if(draft[key]){const o=el('option',draft[key]);o.value=draft[key];$(id).append(o);$(id).value=draft[key];}sections();gallery();render();}
action('save-config',async()=>{notice((await call('/configure',{client_id:$('client-id').value,client_secret:$('client-secret').value,environment:$('environment').value})).message);$('client-secret').value='';$('connection').textContent='Konfiguracja zapisana — połącz konto';});
action('connect',async()=>{await call('/save',collect());const r=await call('/connect',{});location.href=r.url;});
action('disconnect',async()=>{notice((await call('/disconnect',{})).message);$('connection').textContent='Rozłączono';});
action('save-local',async()=>notice((await call('/save',collect())).message));
action('load-template',async()=>{const r=await call('/template',{reference:$('reference').value});$('category').value=r.category||'';$('settings-result').textContent=`Pobrano z: ${r.name}\nCennik dostawy: ${r.template.delivery?.shippingRates?.id||'brak'}\nZwroty: ${r.template.afterSalesServices?.returnPolicy?.id||'brak'}\nReklamacje: ${r.template.afterSalesServices?.impliedWarranty?.id||'brak'}\nGwarancja: ${r.template.afterSalesServices?.warranty?.id||'brak'}`;notice('Pobrano ustawienia sprzedawcy. Wczytaj parametry kategorii i uzupełnij dane nowej części.');render();});
action('load-parameters',async()=>{const r=await call('/parameters',{category:$('category').value});parameters=r.parameters||[];$('parameters').replaceChildren();const values=[...(draft.product_parameters||[]),...(draft.offer_parameters||[])];for(const p of parameters){const box=el('div',undefined,'parameter'),label=el('label',p.name+(p.required?' *':'')),v=el(p.type==='dictionary'?'select':'input');v.id='param-'+p.id;label.htmlFor=v.id;const previous=values.find(x=>x.id===p.id);if(p.type==='dictionary'){v.multiple=!!p.restrictions?.multipleChoices;const empty=el('option','Wybierz');empty.value='';v.append(empty);for(const item of p.dictionary||[]){const o=el('option',item.value);o.value=item.id;o.selected=previous?.valuesIds?.includes(item.id)||false;v.append(o);}}else{v.value=previous?.values?.join('; ')||'';v.placeholder=p.unit||'Wartość';}v.onchange=render;box.append(label,v);if(p.requiredForProduct&&!p.required)box.append(el('small','Wymagany przy tworzeniu nowego produktu'));$('parameters').append(box);}notice('Wczytano pola kategorii. Wartości muszą opisywać sprzedawaną część.');});
action('search-products',async()=>{const r=await call('/products',{phrase:$('phrase').value,category:$('category').value});$('product-id').replaceChildren();const empty=el('option','Nowy produkt — użyj parametrów powyżej');empty.value='';$('product-id').append(empty);for(const p of r.products||[]){const o=el('option',p.name);o.value=p.id;$('product-id').append(o);}notice(`Znaleziono ${(r.products||[]).length} produktów. Sprawdź dokładną zgodność przed wyborem.`);});
action('load-producers',async()=>{const r=await call('/producers',{});$('producer').replaceChildren();const empty=el('option','Nie wybrano');empty.value='';$('producer').append(empty);for(const p of r.responsibleProducers||[]){const o=el('option',p.name||p.producerData?.tradeName||p.id);o.value=p.id;$('producer').append(o);}notice('Pobrano listę producentów. Wybierz producenta tej części.');});
action('save-allegro',async()=>{const data=collect();await call('/save',data);const r=await call('/draft',data);$('saved-status').textContent=r.id?'Szkic Allegro: '+r.id:'Zapis oczekuje na sprawdzenie statusu';notice(r.message+(r.validation?'\n'+JSON.stringify(r.validation):''));});
action('check-status',async()=>{const r=await call('/status',{});$('saved-status').textContent=`Oferta ${r.id}: ${r.publication?.status||'status w trakcie ustalania'}`;notice(JSON.stringify(r,null,2));});
action('publish',async()=>{if(!$('confirm').checked)throw Error('Najpierw sprawdź ofertę i zaznacz potwierdzenie publikacji.');if(!window.confirm(`Opublikować na wybranym koncie Allegro za ${$('price').value} zł, ${$('stock').value} szt.?`))return;const r=await call('/publish',{confirm:true,draft:collect()});notice(r.message);});
$('add-section').onclick=()=>{draft.sections.push({title:'',text:''});sections();render();};
$('photos').onchange=async e=>{try{const files=[...e.target.files];if(draft.images.length+files.length>10)throw Error('Maksymalnie 10 zdjęć.');for(const f of files){if(!['image/png','image/jpeg'].includes(f.type)||f.size>10000000)throw Error('Dodaj PNG/JPG do 10 MB.');const src=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f);});if(draft.images.reduce((n,s)=>n+s.length,0)+src.length>34000000)throw Error('Zdjęcia przekraczają łączny limit 25 MB.');draft.images.push(src);}gallery();render();}catch(e){notice(e.message,true);}finally{$('photos').value='';}};
for(const id of ['name','price','stock','category','safety','producer','product-id'])$(id).addEventListener('input',()=>{if(draft)render();});
(async()=>{try{const r=await(await fetch('/state')).json();csrf=r.csrf;$('client-id').value=r.client_id;$('client-secret').placeholder=r.has_secret?'Zapisany — zostaw puste, by zachować':'';$('environment').value=r.environment;$('connection').textContent=(r.connected?'Konto połączone':'Konto niepołączone')+(r.environment==='sandbox'?' · Sandbox':' · Allegro');$('config').open=!r.connected;draft=r.draft||initial();fill();if(r.saved_offer?.id)$('saved-status').textContent='Zapisana oferta: '+r.saved_offer.id;}catch(e){notice('Nie można uruchomić panelu: '+e.message,true);}})();
